---
# Usage: ansible-playbook -vv -i stellar_cluster -e "node=master:slave" --private-key .ssh/mycloud.key deploy-redis.yaml
# 
# Alternate check
# ansible -i all_nodes_stellar_cluster all --private-key .ssh/mycloud.key -m shell -c ssh -a "systemctl status redis.service"
- hosts: "{{node}}"
  tasks:

  - name: Installing Redis now...
    yum: pkg=redis.x86_64 state=latest

  - name: Checking service state...
    service: name=redis.service state=started enabled=yes
