---
# Usage: ansible-playbook -vv -i stellar_cluster -e "node=master:slave" deploy-redis.yaml
# 
- hosts: "{{node}}"
  tasks:

  - name: Installing Redis now...
    yum: pkg=redis.x86_64 state=latest

  - name: Checking service state...
    service: name=redis.service state=started enabled=yes
