---
# Usage: ansible-playbook -vv -i stellar_cluster -e "node=master:slave state=disabled" dmz-cluster.yaml
#
- hosts: "{{node}}"
  tasks:
  - firewalld: zone=public permanent=true state="{{state}}" port=6379/tcp
  - name: Force updates active
    command: /usr/bin/firewall-cmd --reload
